### ISSUE TITLE
UI not showing properly in production environment!

### ISSUE THREAD

**Issue by sahaavi** [codingforentrepreneurs/SaaS-Foundations#1]
I have followed your tutorial properly but at the end the ui is not working properly. What might be the reason? 
I tried by uploading the vendor files through github but didn't help.

![image](https://github.com/codingforentrepreneurs/SaaS-Foundations/assets/55613672/65100c1d-5216-4bf9-a020-6157f2f315ab)

Thanks in advance. I would really appreciate if you could help me out.

**Comment by kumarpiyush939** [comment]
Check if "python manage.py vendor_pull "
Worked properly then confirm the local cdn folder has all the files.

**Comment by sahaavi** [comment]
Yes, the vendor_pull works properly, and my local CDN has all the files as well. I tried by manually giving all the vendor files without using the vendor_pull command inside dockerfile but didn't work as well.

**Comment by kumarpiyush939** [comment]
What was the issue?

**Comment by sahaavi** [comment]
> What was the issue?

I fixed the issue by using flowbite.min.js 2.3.0 (from cdn) inside the dashboards nav.html. Though I had the same version in the vendors file and I was using that through base.html but somehow that was not working.
